### ISSUE TITLE
Error trying to use bamboolib in conda environment

### ISSUE THREAD

**Issue by matthewbegun** [tkrabel/bamboolib#10]
### Environment

* Operating System: Windows 10 1909
* Python Version: Python 3.7.6
* How did you install bamboolib: conda env (as pip dependency)
* Python packages: 
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
altair=4.0.1=py_0
analytics-python=1.2.9=pypi_0
appdirs=1.4.3=py_1
atomicwrites=1.3.0=py_0
attrs=19.3.0=py_0
autograd=1.3=py_0
autograd-gamma=0.4.1=py_0
backcall=0.1.0=py_0
bamboolib=1.3.0=pypi_0
black=19.10b0=py37_0
blas=1.0=mkl
bleach=3.1.0=py_0
ca-certificates=2019.11.28=hecc5488_0
certifi=2019.11.28=py37_0
cffi=1.13.2=pypi_0
chardet=3.0.4=pypi_0
click=7.0=py_0
colorama=0.4.3=py_0
cryptography=2.8=pypi_0
cycler=0.10.0=py_2
decorator=4.4.1=py_0
defusedxml=0.6.0=py_0
entrypoints=0.3=py37_1000
flake8=3.7.9=py37_0
flake8-bugbear=20.1.4=py_0
freetype=2.10.0=h563cfd7_1
future=0.18.2=py37_0
icc_rt=2019.0.0=h0cc432a_1
icu=64.2=he025d50_1
idna=2.8=pypi_0
importlib_metadata=1.5.0=py37_0
inflect=4.0.0=py37_1
intel-openmp=2019.4=245
ipykernel=5.1.4=py37h5ca1d4c_0
ipython=7.12.0=py37h5ca1d4c_0
ipython_genutils=0.2.0=py_1
ipywidgets=7.5.1=pypi_0
jaraco.itertools=5.0.0=py_0
jedi=0.16.0=py37_0
jinja2=2.11.1=py_0
joblib=0.14.1=py_0
jpeg=9c=hfa6e2cd_1001
json5=0.9.0=py_0
jsonschema=3.2.0=py37_0
jupyter_client=5.3.4=py37_1
jupyter_contrib_core=0.3.3=py_2
jupyter_contrib_nbextensions=0.5.1=py37_0
jupyter_core=4.6.1=py37_0
jupyter_highlight_selected_word=0.2.0=py37_1000
jupyter_latex_envs=1.4.4=py37_1000
jupyter_nbextensions_configurator=0.4.1=py37_0
jupyterlab=1.2.6=py_0
jupyterlab_server=1.0.6=py_0
jupytext=1.3.3=0
kiwisolver=1.1.0=py37he980bc4_0
libblas=3.8.0=14_mkl
libcblas=3.8.0=14_mkl
libclang=9.0.1=default_hf44288c_0
libiconv=1.15=hfa6e2cd_1005
liblapack=3.8.0=14_mkl
libpng=1.6.37=h7602738_0
libsodium=1.0.17=h2fa13f4_0
libxml2=2.9.10=h9ce36c8_0
libxslt=1.1.33=heafd4d3_0
lifelines=0.23.8=py_0
lxml=4.5.0=py37heafd4d3_0
m2w64-gcc-libgfortran=5.3.0=6
m2w64-gcc-libs=5.3.0=7
m2w64-gcc-libs-core=5.3.0=7
m2w64-gmp=6.1.0=2
m2w64-libwinpthread-git=5.0.0.4634.697f757=2
markupsafe=1.1.1=py37hfa6e2cd_0
matplotlib=3.1.3=py37_0
matplotlib-base=3.1.3=py37h2981e6d_0
mccabe=0.6.1=py_1
mistune=0.8.4=py37hfa6e2cd_1000
mkl=2019.4=245
mkl-service=2.3.0=py37hfa6e2cd_0
more-itertools=8.2.0=py_0
msys2-conda-epoch=20160418=1
mypy_extensions=0.4.3=py37_0
nbconvert=5.6.1=py37_0
nbformat=5.0.4=py_0
nodejs=13.7.0=0
notebook=6.0.3=py37_0
numpy=1.17.5=py37hc71023c_0
openssl=1.1.1d=hfa6e2cd_0
packaging=20.1=py_0
pandas=1.0.0=py37he350917_0
pandoc=2.9.1.1=0
pandocfilters=1.4.2=py_1
parso=0.6.0=py_0
pathspec=0.7.0=py_0
patsy=0.5.1=py_0
pickleshare=0.7.5=py37_1000
pip=20.0.2=py37_1
plotly=4.5.0=pypi_0
pluggy=0.13.0=py37_0
prometheus_client=0.7.1=py_0
prompt_toolkit=3.0.3=py_0
py=1.8.1=py_0
pycodestyle=2.5.0=py_0
pycparser=2.19=pypi_0
pyflakes=2.1.1=py_0
pyforest=1.0.2=pypi_0
pygments=2.5.2=py_0
pyparsing=2.4.6=py_0
pyqt=5.12.3=py37h6538335_1
pyqt5-sip=4.19.18=pypi_0
pyqtwebengine=5.12.1=pypi_0
pyrsistent=0.15.6=py37hfa6e2cd_0
pytest=5.3.5=py37_0
python=3.7.6=h5b45d93_2
python-dateutil=2.8.1=py_0
pytz=2019.3=py_0
pywin32=225=py37hfa6e2cd_0
pywinpty=0.5.7=py37_0
pyyaml=5.3=py37hfa6e2cd_0
pyzmq=18.1.1=py37h16f9016_0
qgrid=1.2.0=pypi_0
qt=5.12.5=h7ef1ec2_0
regex=2020.1.8=py37hfa6e2cd_0
requests=2.22.0=pypi_0
retrying=1.3.3=pypi_0
scikit-learn=0.22.1=py37h7208079_1
scipy=1.3.1=py37h29ff71c_0
seaborn=0.10.0=py_0
send2trash=1.5.0=py_0
setuptools=45.1.0=py37_0
six=1.14.0=py37_0
sqlite=3.30.1=hfa6e2cd_0
statsmodels=0.11.0=py37hfa6e2cd_0
terminado=0.8.3=py37_0
testpath=0.4.4=py_0
toml=0.10.0=py_0
toolz=0.10.0=py_0
tornado=6.0.3=py37hfa6e2cd_0
traitlets=4.3.3=py37_0
typed-ast=1.4.1=py37hfa6e2cd_0
typing_extensions=3.7.4.1=py37_0
urllib3=1.25.8=pypi_0
vc=14.1=h0510ff6_4
vega_datasets=0.8.0=py_0
vs2015_runtime=14.16.27012=hf0eaf9b_1
wcwidth=0.1.8=py_0
webencodings=0.5.1=py_1
wheel=0.34.2=py37_0
widgetsnbextension=3.5.1=pypi_0
wincertstore=0.2=py37_1003
winpty=0.4.3=4
yaml=0.2.2=hfa6e2cd_1
zeromq=4.3.2=h6538335_2
zipp=2.1.0=py_0
zlib=1.2.11=h2fa13f4_1006
```
* If bamboolib is used with JupyterLab: JupyterLab extensions: 
```
JupyterLab v1.2.6
Known labextensions:
   app dir: C:\Users\z3391967\.conda\envs\testes\share\jupyter\lab
        @8080labs/qgrid v1.1.1 enabled  ok
        @jupyter-widgets/jupyterlab-manager v1.1.0 enabled  ok
        bamboolib v1.3.0 enabled  ok
        jupyterlab-jupytext v1.1.1 enabled  ok
        jupyterlab-plotly v1.5.0 enabled  ok
        plotlywidget v1.5.0 enabled  ok
        pyforest v0.0.1 enabled  ok*

   local extensions:
        pyforest: C:\Users\z3391967\.conda\envs\testes\lib\site-packages\pyforest
```
* If bamboolib is used with Jupyter Notebook: Notebook extension:
```
Known nbextensions:
  config dir: C:\Users\z3391967\.jupyter\nbconfig
    notebook section
      pyforest/nbextension enabled
      - Validating: ok
  config dir: C:\Users\z3391967\.conda\envs\testes\etc\jupyter\nbconfig
    notebook section
      bamboolib/extension enabled
      - Validating: ok
      jupytext/index enabled
      - Validating: ok
      plotlywidget/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
      qgrid/extension enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```
### Description of Issue
Attempting to load bamboolib ui for dataframe raises.
* What did you expect to happen?

bamboolib ui should load over data frame

* What happened instead?

Raises exception:
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\z3391967\.conda\envs\testes\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\z3391967\.conda\envs\testes\lib\threading.py", line 1177, in run
    self.function(*self.args, **self.kwargs)
  File "bamboolib\setup\ipython_display.py", line 124, in bamboolib.setup.ipython_display.lazy_load_wrangler.load_wrangler
  File "bamboolib\wrangler.py", line 257, in bamboolib.wrangler.create_wrangler_for_ipython_display
  File "bamboolib\wrangler.py", line 239, in bamboolib.wrangler._show
  File "bamboolib\wrangler.py", line 54, in bamboolib.wrangler.authenticate.patched_init_function
  File "bamboolib\wrangler.py", line 70, in bamboolib.wrangler.Wrangler.__init__
  File "bamboolib\grid.py", line 658, in bamboolib.grid.show_grid
  File "bamboolib\grid.py", line 780, in bamboolib.grid.BamGridWidget.__init__
  File "bamboolib\grid.py", line 984, in bamboolib.grid.BamGridWidget._update_df
  File "bamboolib\grid.py", line 1054, in bamboolib.grid.BamGridWidget._update_table
AttributeError: module 'pandas.core' has no attribute 'index'
```
### Reproduction Steps

1. install environment in conda
2. install extensions (or not, happens either way)
3. run test (from [the repo](https://github.com/tkrabel/bamboolib/blob/master/installation/bamboolib_test_run/with_virtual_environment.md))

### What steps have you taken to resolve this already?

- Restart jupyter
- Recreate environment

### Anything else?

Works fine in docker, not sure what I'm missing in my local setup.

**Comment by matthewbegun** [comment]
I am creating the conda env with the following environment.yml file:

```yml
name: testes
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - python=3.7
  - pip
  - jupyterlab
  - jupyter_contrib_nbextensions
  - nodejs
  - jupytext
  - black
  - pytest
  - flake8-bugbear
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - altair
  - vega_datasets
  - seaborn
  - statsmodels
  - scikit-learn
  - lifelines
  - pip:
      - pyforest
      - bamboolib
```

**Comment by 8080labs** [comment]
Hi Matthew,

thank you for your detailed bug report!
This bug is due to the major update of pandas to 1.0.0 last week. Currently bamboolib does not yet support pandas 1.0.0 but only pandas versions below 1.0.0.

In version 1.4.0 and 1.4.1 of bamboolib that we released today, we fixed the requirements to make sure that pandas is below 1.0.0.
This will fix your bug when you create your next virtual environment.

In case that you need to work with pandas 1.0.0, please let us know.

Have a great day,
Florian

**Comment by matthewbegun** [comment]
Ok thanks!
